# Generated by Django 3.2.23 on 2025-12-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=8, null=True),
        ),
    ]
