# Generated by Django 4.2.17 on 2025-12-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False, help_text='Show this product in Flash Sale section'),
        ),
    ]
