# Generated by Django 4.2.17 on 2026-01-04 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_add_guest_checkout_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Business owner's email", max_length=254, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='approved', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage', max_digits=5)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_businesses', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorStorefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text='Hero banner image (recommended: 1920x600)', null=True, upload_to='vendors/hero/')),
                ('hero_title', models.CharField(blank=True, help_text='Main headline on hero section', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Subtitle or description', max_length=500)),
                ('hero_cta_text', models.CharField(default='Shop Now', help_text='Call to action button text', max_length=50)),
                ('hero_cta_link', models.CharField(blank=True, help_text='CTA button link (leave empty for products page)', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Store logo (recommended: 200x50)', null=True, upload_to='vendors/logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon for browser tab', null=True, upload_to='vendors/favicons/')),
                ('primary_color', models.CharField(default='#6366f1', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', help_text='Secondary color (hex)', max_length=7)),
                ('accent_color', models.CharField(default='#06b6d4', help_text='Accent color for highlights (hex)', max_length=7)),
                ('product_layout', models.CharField(choices=[('grid', 'Grid Layout'), ('list', 'List Layout'), ('masonry', 'Masonry Layout')], default='grid', max_length=20)),
                ('products_per_page', models.PositiveIntegerField(default=12)),
                ('show_flash_sale', models.BooleanField(default=True, help_text='Show flash sale section on storefront')),
                ('show_categories', models.BooleanField(default=True, help_text='Show category navigation')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (defaults to business name)', max_length=160)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description', max_length=320)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to='vendors.business')),
            ],
            options={
                'verbose_name': 'Vendor Storefront',
                'verbose_name_plural': 'Vendor Storefronts',
            },
        ),
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendors.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_from_vendor', models.BooleanField(default=False, help_text='True if sent by vendor, False if sent by customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='vendors.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_messages', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Related order (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_messages', to='orders.order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='vendors.vendormessage')),
            ],
            options={
                'verbose_name': 'Vendor Message',
                'verbose_name_plural': 'Vendor Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
