# Generated by Django 4.2.17 on 2026-01-05 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField(help_text='Describe your business and what you plan to sell')),
                ('category', models.CharField(choices=[('electronics', 'Electronics & Gadgets'), ('fashion', 'Fashion & Apparel'), ('beauty', 'Beauty & Personal Care'), ('home', 'Home & Living'), ('food', 'Food & Beverages'), ('sports', 'Sports & Outdoors'), ('books', 'Books & Stationery'), ('toys', 'Toys & Games'), ('automotive', 'Automotive'), ('other', 'Other')], max_length=50)),
                ('address', models.TextField()),
                ('business_document', models.FileField(blank=True, help_text='Business registration or tax document (optional)', null=True, upload_to='vendor_applications/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info', 'More Info Needed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason shown to user if rejected')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='vendors.business')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Application',
                'verbose_name_plural': 'Vendor Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
