# Generated by Django 4.2.17 on 2026-01-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter Pack'), ('professional', 'Professional Pack')], default='starter', help_text='Current subscription plan', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, help_text='When paid subscription started', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial Period'), ('active', 'Active Subscription'), ('expired', 'Trial Expired'), ('cancelled', 'Cancelled')], default='trial', help_text='Current subscription status', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='When the trial period ends', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_expiry_email_sent',
            field=models.BooleanField(default=False, help_text='Whether trial expiry reminder email has been sent'),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, help_text='When the trial period started', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='welcome_message_shown',
            field=models.BooleanField(default=False, help_text='Whether welcome message has been shown after approval'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='selected_plan',
            field=models.CharField(choices=[('starter', 'Starter Pack'), ('professional', 'Professional Pack')], default='starter', help_text='Subscription plan selected by the applicant', max_length=20),
        ),
    ]
