# Generated by Django 4.2.17 on 2026-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_business_plan_business_subscription_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Your date of birth (mm/dd/yyyy)', null=True),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='phone',
            field=models.CharField(help_text='Phone number with country code (e.g., +977-XXXXXXXXXX)', max_length=20),
        ),
    ]
