# Generated by Django 4.2.17 on 2026-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorapplication_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstorefront',
            name='layout_template',
            field=models.CharField(default='classic', help_text='Layout template style (classic, modern, minimal)', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='section_order',
            field=models.TextField(blank=True, default='hero,categories,featured,new-arrivals,deals,testimonials,newsletter', help_text='Comma-separated order of storefront sections'),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='sections_enabled',
            field=models.TextField(blank=True, default='hero,categories,featured,new-arrivals,newsletter', help_text='Comma-separated list of enabled sections'),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='show_featured',
            field=models.BooleanField(default=True, help_text='Show featured products section'),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='show_hero',
            field=models.BooleanField(default=True, help_text='Show hero banner section'),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='show_new_arrivals',
            field=models.BooleanField(default=True, help_text='Show new arrivals section'),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='show_newsletter',
            field=models.BooleanField(default=True, help_text='Show newsletter subscription section'),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='show_testimonials',
            field=models.BooleanField(default=False, help_text='Show testimonials section'),
        ),
    ]
