# Generated by Django 4.2.17 on 2026-01-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorstorefront_layout_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstorefront',
            name='dashboard_accent_color',
            field=models.CharField(default='#10b981', help_text='Dashboard accent color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='dashboard_primary_color',
            field=models.CharField(default='#6366f1', help_text='Dashboard primary color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='dashboard_sidebar_color',
            field=models.CharField(default='#111827', help_text='Dashboard sidebar background color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='header_style',
            field=models.CharField(choices=[('classic', 'Classic - Centered Logo'), ('modern', 'Modern - Left Logo + Mega Menu'), ('minimal', 'Minimal - Hamburger Menu')], default='classic', help_text='Header layout style (Professional plan)', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_cta_link_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_cta_link_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_cta_text_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_cta_text_3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_image_2',
            field=models.ImageField(blank=True, help_text='Second hero image for slider (1920x600)', null=True, upload_to='vendors/hero/'),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_image_3',
            field=models.ImageField(blank=True, help_text='Third hero image for slider (1920x600)', null=True, upload_to='vendors/hero/'),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_overlay_color',
            field=models.CharField(default='#000000', help_text='Overlay color for hero banner (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_overlay_opacity',
            field=models.PositiveIntegerField(default=30, help_text='Overlay opacity percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_style',
            field=models.CharField(choices=[('full_width', 'Full-Width Image'), ('split', 'Split - Image + Text Side by Side'), ('slider', 'Slider/Carousel')], default='full_width', help_text='Hero banner layout style (Professional plan)', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_subtitle_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_subtitle_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_title_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='hero_title_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='storefront_template',
            field=models.CharField(choices=[('classic', 'Classic Template'), ('modern', 'Modern Template'), ('minimal', 'Minimal Template')], default='classic', help_text='Complete storefront template style', max_length=20),
        ),
    ]
