# Generated by Django 4.2.17 on 2026-01-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_add_advanced_storefront_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, help_text='Business logo (optional)', null=True, upload_to='business_logos/'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='logo',
            field=models.ImageField(blank=True, help_text='Your company logo (optional - you can also just use your business name)', null=True, upload_to='vendor_applications/logos/'),
        ),
    ]
