# Generated by Django 4.2.17 on 2026-01-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_add_logo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstorefront',
            name='about_mission',
            field=models.TextField(blank=True, help_text='Your mission statement - what drives your business'),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='about_story',
            field=models.TextField(blank=True, help_text="Your store's story - how you started, your journey"),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='about_tagline',
            field=models.CharField(blank=True, help_text='Short tagline below the title', max_length=300),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='about_title',
            field=models.CharField(blank=True, help_text="About page headline (defaults to 'About [Store Name]')", max_length=200),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='about_vision',
            field=models.TextField(blank=True, help_text='Your vision - where you see your business going'),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='contact_address',
            field=models.CharField(blank=True, help_text='Full business address', max_length=300),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='contact_city',
            field=models.CharField(blank=True, default='Nepal', help_text='City/Country', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='contact_hours',
            field=models.CharField(blank=True, default='Sun - Fri: 10 AM - 6 PM', help_text='Business hours', max_length=200),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='contact_hours_note',
            field=models.CharField(blank=True, default='Saturday: Closed', help_text='Additional note about hours', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorstorefront',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=50),
        ),
    ]
