# Generated by Django 4.2.17 on 2026-01-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_product_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_products', models.ManyToManyField(blank=True, help_text='All products to show in the demo store', related_name='demo_all', to='products.product')),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories to display in the demo', related_name='demo_categories', to='products.category')),
                ('featured_products', models.ManyToManyField(blank=True, help_text='Products to show in the featured section', related_name='demo_featured', to='products.product')),
                ('flash_sale_products', models.ManyToManyField(blank=True, help_text='Products to show in the flash sale section', related_name='demo_flash_sale', to='products.product')),
                ('new_arrival_products', models.ManyToManyField(blank=True, help_text='Products to show in the new arrivals section', related_name='demo_new_arrivals', to='products.product')),
            ],
            options={
                'verbose_name': 'Demo Settings',
                'verbose_name_plural': 'Demo Settings',
            },
        ),
    ]
