# Generated by Django 4.2.17 on 2026-01-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this product has been viewed'),
        ),
    ]
