# Generated by Django 4.2.17 on 2026-01-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-laptop', 'Electronics'), ('fa-tshirt', 'Fashion & Clothing'), ('fa-home', 'Home & Garden'), ('fa-futbol', 'Sports & Outdoors'), ('fa-spa', 'Beauty & Personal Care'), ('fa-book', 'Books & Media'), ('fa-gamepad', 'Toys & Games'), ('fa-shopping-basket', 'Food & Grocery'), ('fa-heartbeat', 'Health & Wellness'), ('fa-gem', 'Jewelry & Watches'), ('fa-car', 'Automotive'), ('fa-baby', 'Baby & Kids'), ('fa-paw', 'Pet Supplies'), ('fa-briefcase', 'Office & Business'), ('fa-music', 'Music & Instruments')], default='fa-shopping-basket', max_length=50),
        ),
    ]
